name: Build and Publish WSL2 Image

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up WSL2
        uses: vedantmgoyal9/setup-wsl2@main
        with:
          distro: 'Debian'
          enable-systemd: true

      - name: Install Software in WSL
        shell: wsl-run {0}
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sL https://containerlab.dev/setup | sudo -E bash -s "all"

      - name: Export WSL Distribution
        shell: powershell
        run: |
          $exportPath = "$env:USERPROFILE\wsl-images\clab-wsl2.tar"
          New-Item -ItemType Directory -Force -Path (Split-Path $exportPath)
          Write-Host "Exporting Debian to $exportPath"
          wsl --export Debian $exportPath

          $importLocation = "$env:USERPROFILE\wsl-images\clab-wsl2-imported"
          Write-Host "Importing clab-wsl2 to $importLocation"
          wsl --import clab-wsl2 $importLocation $exportPath --version 2

          $finalExportPath = "$env:USERPROFILE\wsl-images\clab-wsl2-final.tar"
          Write-Host "Exporting clab-wsl2 to $finalExportPath"
          wsl --export clab-wsl2 $finalExportPath

          echo "FINAL_EXPORT_PATH=$finalExportPath" >> $env:GITHUB_ENV
          Write-Host "Exported final tar to $finalExportPath"

      - name: List Exported Files
        shell: powershell
        run: |
          Write-Host "Listing files in $env:USERPROFILE\wsl-images"
          Get-ChildItem -Path "$env:USERPROFILE\wsl-images" -Recurse

      - name: Upload WSL Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: clab-wsl2
          path: ${{ env.FINAL_EXPORT_PATH }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.FINAL_EXPORT_PATH }}
          asset_name: clab-wsl2-final.tar
          asset_content_type: application/x-tar