name: Build and Publish WSL2 Image

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write  # Grants permission to create releases and upload assets

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up WSL2
        uses: vedantmgoyal9/setup-wsl2@main
        with:
          distro: 'Ubuntu-24.04'  # Specify the Ubuntu version
          enable-systemd: true

      - name: Install Software in WSL
        shell: wsl-run {0}
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y htop
          # Replace 'htop' with the packages you want to install

      - name: Export WSL Distribution
        shell: powershell
        run: |
          $exportPath = "$env:USERPROFILE\wsl-images\clab-wsl2.tar"
          New-Item -ItemType Directory -Force -Path (Split-Path $exportPath)
          wsl --export Ubuntu-24.04 $exportPath

          # Import the distro with a new name 'clab-wsl2'
          wsl --import clab-wsl2 $env:USERPROFILE\wsl-images\clab-wsl2-imported $exportPath --version 2

          # Optionally unregister the original distro if you don't need it anymore
          # wsl --unregister Ubuntu-24.04

          # Re-export the imported distro to have the desired name in the tar file
          $finalExportPath = "$env:USERPROFILE\wsl-images\clab-wsl2-final.tar"
          wsl --export clab-wsl2 $finalExportPath

      - name: Upload WSL Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: clab-wsl2
          path: ${{ env.USERPROFILE }}\wsl-images\clab-wsl2-final.tar

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v1.0.0'  # Update version as needed
          release_name: 'Custom WSL2 clab-wsl2 Image'
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.USERPROFILE }}\wsl-images\clab-wsl2-final.tar
          asset_name: clab-wsl2-final.tar
          asset_content_type: application/x-tar